### ISSUE TITLE
File upload from manifest fails on local machine

### ISSUE THREAD

**Issue by kdim1918** [neufeld/AXIOME3-GUI#4]
Hello,

I installed AXIOME3-GUI according to the instructions (https://github.com/neufeld/AXIOME3-GUI) on my local machine (macbook pro running OSX 10.13.6). I can access the gui when I go to localhost:8080. When I upload the example manifest file (https://github.com/neufeld/AXIOME3-GUI/wiki/Tutorial---Main) the upload fails with error:

"File referenced on line 2 could not be found (/Users/homedir/Downloads/drive_download-1/sample1_forward.fastq.gz)."

The manifest looks like this:

sample-id,absolute-filepath,direction
sample_1,/Users/homedir/Downloads/drive_download-1/sample1_forward.fastq.gz,forward
sample_1,/Users/homedir/Downloads/drive_download-1/sample1_reverse.fastq.gz,reverse
sample_2,/Users/homedir/Downloads/drive_download-1/sample2_forward.fastq.gz,forward
sample_2,/Users/homedir/Downloads/drive_download-1/sample2_reverse.fastq.gz,reverse
sample_3,/Users/homedir/Downloads/drive_download-1/sample3_forward.fastq.gz,forward
sample_3,/Users/homedir/Downloads/drive_download-1/sample3_reverse.fastq.gz,reverse

As far as I can tell, everything is correct. But it can't find the files on my local machine. Any idea what's happening?

**Comment by danielm710** [comment]
Turns out there was an issue with the Docker volume name resolution on MacOS and Windows OS. I just pushed the new code to the repo. Please uninstall/remove AXIOME3-GUI images, run `git pull`, and reinstall the application.

**Comment by kdim1918** [comment]
Thanks Daniel. I've uninstalled AXIOME3-GUI, run git pull, and reinstalled the application as you recommended. The file upload with the original manifest works.
